from .CompfyuiOllama import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .OllamaSongwriterV3 import NODE_CLASS_MAPPINGS as SONG_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SONG_NODE_NAMES
from .deprecated_nodes import NODE_CLASS_MAPPINGS as DEPRECATED_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DEPRECATED_NODE_DISPLAY_NAME_MAPPINGS

#merge deprecated mappings
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **DEPRECATED_NODE_CLASS_MAPPINGS, **SONG_NODE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **DEPRECATED_NODE_DISPLAY_NAME_MAPPINGS, **SONG_NODE_NAMES}


WEB_DIRECTORY = "./web"
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
